[[servers]]
name = "notion"
enabled_tools = []
disabled_tools = [
    "notion-create-comment",
    "notion-create-database",
    "notion-create-pages",
    "notion-create-view",
    "notion-duplicate-page",
    "notion-fetch",
    "notion-get-comments",
    "notion-get-teams",
    "notion-get-users",
    "notion-move-pages",
    "notion-query-database-view",
    "notion-query-meeting-notes",
    "notion-update-data-source",
    "notion-update-page",
    "notion-update-view",
]

[servers.type]
type = "http"
url = "https://mcp.notion.com/mcp"

[tunnel]
mode = "disabled"
